CREATE TABLE RGON_M (
    RGON_CD CHAR(2) NOT NULL,
    RGON_NM VARCHAR(40) NOT NULL,
    RGON_USE_TYP CHAR(1) NOT NULL,
    DISP_ORDER INT NOT NULL,
    DELETE_FLG CHAR(1) NOT NULL,
    PRIMARY KEY (RGON_CD)
);

CREATE TABLE PREF_M (
    PREF_CD CHAR(2) NOT NULL,
    PREF_NM VARCHAR(40) NOT NULL,
    RGON_CD CHAR(2),
    DELETE_FLG CHAR(1) NOT NULL,
    PRIMARY KEY (PREF_CD)
);

CREATE TABLE REF_M (
    REF_CD VARCHAR(10) NOT NULL,
    REF_NM VARCHAR(100) NOT NULL,
    REF_KN VARCHAR(200) NOT NULL,
    TEL_NO VARCHAR(13),
    PREF_CD CHAR(2),
    RGON_CD CHAR(2),
    DELETE_FLG CHAR(1) NOT NULL,
    PRIMARY KEY (REF_CD)
);

CREATE TABLE URL_M (
    URL_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    REF_CD VARCHAR(10) NOT NULL,
    URL_ADDR VARCHAR(256) NOT NULL,
    DELETE_FLG CHAR(1) NOT NULL
);
